[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charming = { path = "../../charming", features = ["wasm"] }
leptos = { version = "0.4.10", features = ["csr"] }
